### ISSUE TITLE
Links on the main README index should be URL encoded

### ISSUE THREAD

**Issue by taylorthurlow** [pjambet/til-rb#1]
I added a new note with the title

```
Ruby 2.7 adds Enumerable#filter_map
```

It added fine, but the URL generated for the README.md entry is:

```
https://github.com/taylorthurlow/til/blob/master/ruby/2020-06-25_ruby-2.7-adds-enumerable#filter_map.md
```

This URL 404s. The true URL for the new file is:

```
https://github.com/taylorthurlow/til/blob/master/ruby/2020-06-25_ruby-2.7-adds-enumerable%23filter_map.md
```

Notice the `#` encoded as `%23`.

**Comment by pjambet** [comment]
Hey!

Thanks for filing this, I will work on a fix right now, because this is definitely something I would have run into at some point, so thanks for being the guinea pig here I guess.

I'll let you know when the new version is released, it should be really quick!

**Comment by pjambet** [comment]
I'll release a new version, 0.0.7 later today, I'll let you know when it's pushed on rubygems.

**Comment by pjambet** [comment]
[0.0.7 was released](https://rubygems.org/gems/til-rb/versions/0.0.7) and contains this fix. Thanks again!

**Comment by pjambet** [comment]
Looks I was way too optimistic, doesn't seem solved, nevermind, and apologies, I will thoroughly test it and update when it's _actually_ fixed ... 🤦🏻‍♂️

EDIT: Yeah, I introduced a new bug, I always URI encode the filename now, instead of "just" encoding in the link, kinda embarassing, but fixing it now, for real for real

**Comment by pjambet** [comment]
Soooo, 0.0.8 is out now, and I _actually_ tested it on my own repo before publishing this time, [this commit](https://github.com/pjambet/til/commit/c5bc5480ba7e2bfa44a29605cd8e8b5912e88f32) was created with 0.0.8. It should be fixed, for real this time.
