### ISSUE TITLE
Consider using different environment variable names

### ISSUE THREAD

**Issue by taylorthurlow** [pjambet/til-rb#2]
`GH_REPO` and `GH_TOKEN` are generic enough where you need to worry about other applications making the same mistake, and using the same environment variable name. Especially when asking users to set these permanently, I suggest something like `TIL_RB_GITHUB_REPO` and `TIL_RB_GITHUB_TOKEN`. Realistically there's no negative to them being longer because you never need to re-type it after configuration.

Ultimately these should be in their own configuration file, probably under `~/.config`, but I'm sure that's being considered.

**Comment by pjambet** [comment]
Hey (again),

To answer your two questions:

- You're absolutely correct about the name, I will rename the variables with `TIL_` prefix right now, this was a huge oversight on my end
- Storing the values under `~/.config` is something that was on my radar, I also wanted to add a `configure` command that would create the necessary files and folders for you, but we can definitely add the ability to read from a config file first and the `configure` command (which would be a little bit more work) later.

Thanks again!

**Comment by pjambet** [comment]
As mentioned in #1, [0.0.7 was released](https://rubygems.org/gems/til-rb/versions/0.0.7), it also contains this change.

I created [another issue](#5) for the config file thing, and will create another one later on for the `configure` command I want.

Thanks, and please keep sharing feedback or issues, really really appreciate it!
